// GENERATED by scripts/build-image-manifest.mjs — do not edit by hand.
// Run `npm run extract:design` after replacing any image.

export interface ImageAsset {
  readonly src: string;
  readonly width: number;
  readonly height: number;
}

export const IMAGES = {
  "hs-emblem-burgundy": { src: "/images/brand/hs-emblem-burgundy.png", width: 273, height: 309 },
  "hs-emblem-cream": { src: "/images/brand/hs-emblem-cream.png", width: 273, height: 309 },
  "hs-emblem-gold": { src: "/images/brand/hs-emblem-gold.png", width: 273, height: 309 },
  "bg-scents-hero": { src: "/images/scents/bg-scents-hero.png", width: 1260, height: 1231 },
  "bottle-berry-cloud": { src: "/images/scents/bottle-berry-cloud.png", width: 1024, height: 572 },
  "bottle-citrus-rose": { src: "/images/scents/bottle-citrus-rose.png", width: 1024, height: 572 },
  "bottle-golden-vanilla": {
    src: "/images/scents/bottle-golden-vanilla.png",
    width: 1024,
    height: 572,
  },
  "bottle-ivory-petals": {
    src: "/images/scents/bottle-ivory-petals.png",
    width: 1024,
    height: 572,
  },
  "bottle-lychee-rose": { src: "/images/scents/bottle-lychee-rose.png", width: 1024, height: 572 },
  "bottle-midnight-vanilla": {
    src: "/images/scents/bottle-midnight-vanilla.png",
    width: 1024,
    height: 572,
  },
  "bottle-saffron-amber": {
    src: "/images/scents/bottle-saffron-amber.jpeg",
    width: 1024,
    height: 572,
  },
  "bottle-velvet-coffee": {
    src: "/images/scents/bottle-velvet-coffee.png",
    width: 1024,
    height: 572,
  },
  "photo-artist-pour": { src: "/images/photos/photo-artist-pour.png", width: 1197, height: 1204 },
  "photo-bottle-hand": { src: "/images/photos/photo-bottle-hand.png", width: 1008, height: 889 },
  "photo-cart-curtain": { src: "/images/photos/photo-cart-curtain.png", width: 1134, height: 1491 },
  "photo-cart-hero": { src: "/images/photos/photo-cart-hero.png", width: 1134, height: 1272 },
  "photo-closeup-tray": { src: "/images/photos/photo-closeup-tray.png", width: 1109, height: 1245 },
  "photo-hero-bg": { src: "/images/photos/photo-hero-bg.png", width: 1260, height: 1231 },
  "photo-setup-blue": { src: "/images/photos/photo-setup-blue.png", width: 1159, height: 1286 },
  "photo-setup-sage": { src: "/images/photos/photo-setup-sage.png", width: 1159, height: 1176 },
  "photo-step1-choose": { src: "/images/photos/photo-step1-choose.png", width: 1109, height: 999 },
  "photo-step2-blend": { src: "/images/photos/photo-step2-blend.png", width: 983, height: 1094 },
  "photo-step3-bottles": {
    src: "/images/photos/photo-step3-bottles.png",
    width: 1159,
    height: 1108,
  },
} as const satisfies Record<string, ImageAsset>;

export type ImageKey = keyof typeof IMAGES;

export function image(key: ImageKey): ImageAsset {
  return IMAGES[key];
}
