// GENERATED by scripts/build-media-manifest.mjs — do not edit by hand.
// Run `npm run media:manifest` after adding or replacing any asset.

export interface ImageAsset {
  readonly src: string;
  readonly width: number;
  readonly height: number;
}

export interface VideoAsset extends ImageAsset {
  /** Frame shown before playback, and the still that reduced motion keeps. */
  readonly poster: string;
}

export const IMAGES = {
  "brand-bottles": { src: "/images/brand/brand-bottles.jpg", width: 1080, height: 1440 },
  "brand-cart": { src: "/images/brand/brand-cart.jpg", width: 1065, height: 1477 },
  "brand-glasses": { src: "/images/brand/brand-glasses.jpg", width: 1080, height: 1440 },
  "brand-gold-stand": { src: "/images/brand/brand-gold-stand.jpg", width: 1086, height: 1448 },
  "brand-lamp-row": { src: "/images/brand/brand-lamp-row.jpg", width: 1080, height: 1440 },
  "brand-tower": { src: "/images/brand/brand-tower.jpg", width: 1320, height: 1760 },
  "hs-mark": { src: "/images/brand/hs-mark.png", width: 672, height: 632 },
  "bg-scents-hero": { src: "/images/scents/bg-scents-hero.png", width: 1260, height: 1231 },
  "bottle-berry-cloud": { src: "/images/scents/bottle-berry-cloud.png", width: 1024, height: 572 },
  "bottle-citrus-rose": { src: "/images/scents/bottle-citrus-rose.png", width: 1024, height: 572 },
  "bottle-golden-vanilla": { src: "/images/scents/bottle-golden-vanilla.png", width: 1024, height: 572 },
  "bottle-ivory-petals": { src: "/images/scents/bottle-ivory-petals.png", width: 1024, height: 572 },
  "bottle-lychee-rose": { src: "/images/scents/bottle-lychee-rose.png", width: 1024, height: 572 },
  "bottle-midnight-vanilla": { src: "/images/scents/bottle-midnight-vanilla.png", width: 1024, height: 572 },
  "bottle-saffron-amber": { src: "/images/scents/bottle-saffron-amber.jpeg", width: 2750, height: 1536 },
  "bottle-velvet-coffee": { src: "/images/scents/bottle-velvet-coffee.png", width: 1024, height: 572 },
  "photo-artist-pour": { src: "/images/photos/photo-artist-pour.png", width: 1197, height: 1204 },
  "photo-bottle-hand": { src: "/images/photos/photo-bottle-hand.png", width: 1008, height: 889 },
  "photo-closeup-tray": { src: "/images/photos/photo-closeup-tray.png", width: 1109, height: 1245 },
  "photo-step1-choose": { src: "/images/photos/photo-step1-choose.png", width: 1109, height: 999 },
  "photo-step2-blend": { src: "/images/photos/photo-step2-blend.png", width: 983, height: 1094 },
  "photo-step3-bottles": { src: "/images/photos/photo-step3-bottles.png", width: 1159, height: 1108 },
} as const satisfies Record<string, ImageAsset>;

export const VIDEOS = {
  "reel-1": { src: "/video/reel-1.mp4", poster: "/video/reel-1-poster.jpg", width: 576, height: 1024 },
  "reel-2": { src: "/video/reel-2.mp4", poster: "/video/reel-2-poster.jpg", width: 576, height: 1024 },
  "reel-3": { src: "/video/reel-3.mp4", poster: "/video/reel-3-poster.jpg", width: 576, height: 1024 },
  "reel-4": { src: "/video/reel-4.mp4", poster: "/video/reel-4-poster.jpg", width: 576, height: 1024 },
} as const satisfies Record<string, VideoAsset>;

export type ImageKey = keyof typeof IMAGES;
export type VideoKey = keyof typeof VIDEOS;

export function image(key: ImageKey): ImageAsset {
  return IMAGES[key];
}

export function video(key: VideoKey): VideoAsset {
  return VIDEOS[key];
}
